### ISSUE TITLE
ネットワークエラーでプロセスが終了しないようにする

### ISSUE THREAD

**Issue by jujunjun110** [jujunjun110/ususama#5]
現状、以下のようなエラーによってプログラムが停止してしまう。
エラーハンドリングなどで、プログラム自体の停止はしないようにしたい。

```
Traceback (most recent call last):
  File "main.py", line 53, in <module>
    slack.post_status(bool(room1['status']), bool(room2['status']))
  File "/home/pi/ususama/slack.py", line 18, in post_status
    'profile': profile
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 94, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 49, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 457, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 569, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 407, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', gaierror(-2, 'Name or service not known'))
```

**Comment by jujunjun110** [comment]
ちなみにこのときsshも繋がらなくなったので、Slack側の問題ではなくWifi側の問題なのはほぼ間違いないと思う。

**Comment by jujunjun110** [comment]
`ps ux | grep main.py`

して0件だったら main.py を実行するcrontab を定期的に走らせるのもありかなぁ。

**Comment by jujunjun110** [comment]
↑実装したのでエラーで止まっちゃうのはそんなに問題ない感じになった

**Comment by jujunjun110** [comment]
リトライもするようにしたい

**Comment by jujunjun110** [comment]
リトライするようにした
